name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
 pull_request:
jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy: 
      matrix:
        node-version: [18.13.x]
          npm install
          npm run build --if-present
          npm run test

