name: test-coverage-actions
run-name: TestCoverage GitHub Actions

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  out-put-coverage:
    runs-on: ubuntu-latest
    outputs:
      json_string: ${{ steps.runner-project.outputs.json_string }}
      json_array: ${{ steps.runner-project.outputs.json_array }}
      array: ${{ steps.runner-project.outputs.array }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test-ci
      - name: Cat Sammary
        id: runner-project
        run: |
          old_ifs=$IFS
          IFS=''
          declare -a array=() 
          while IFS='' read -r line
          do
              array+=($line)
          done < karma/coverage/--code-coverage/coverage.txt
          IFS=$old_ifs

          json_array=$(printf "%s\n" "${array[@]}" | jq -R . | jq -s)
          json_string=$(jq -n --arg array "$json_array" '$array')

          echo $json_array
          echo $json_string

          echo "json_string=$json_string" >> $GITHUB_OUTPUT
  post-coverage-report-to-PR: 
    needs: out-put-coverage
    runs-on: ubuntu-latest
    steps:
      -  name: Post coverage report to PR
         uses: actions/github-script@v4
         with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(${{ needs.out-put-coverage.outputs.json_string }});
            const parse = JSON.parse(${{needs.out-put-coverage.outputs.json_string}});
            console.log(parse);
      - name: Cat summary
        run: echo ${{ needs.out-put-coverage.outputs.json_string }}
